### ISSUE TITLE
Option to set/remember terminal size and position

### ISSUE THREAD

**Issue by skipmeister123** [felixse/FluentTerminal#18]
I would like to be able to resize the terminal window and have the size be remembered between launches.  I would also like for it to remember the window position between launches.

**Comment by felixse** [comment]
Should be fixed now 😃

**Comment by Linard11** [comment]
I still have this issue in v1.10.0 Neither positions nor sizes are retained between launches

**Comment by felixse** [comment]
This is fixed on master, and will be part of the next release.
I admit its a bit confusing this way, so from now on I will only close issues once they are released.

**Comment by ericcornelissen** [comment]
Related issue, so I figured I would continue on this thread. When you resize the settings window it determines the size of the main window, for example ⬇️ Note that this is not reproducible if you close the settings window **before** the main window.

![resize-issue-preview](https://user-images.githubusercontent.com/3742559/48093700-be06a880-e218-11e8-9564-0aa0ee61598c.gif)

**Comment by skipmeister123** [comment]
Also, what's more important to me than the window size is the number of 
rows and columns displayed. I would like to be able to specify those 
values, and the window will be sized properly, regardless of what font I'm 
using.
--
Hans Kokx

**Comment by ahallicks** [comment]
I am currently running the latest version (v0.7.0.0) and I now have this issue. If I close the app and start it again it always starts on my left monitor about 200px from the top and left and about 60% the size of the screen.

I always drag it to the bottom-left of that monitor but on subsequent starts, it is in the original position every time.

**Comment by qbattersby** [comment]
Yea mine also does not remember past position etc.
