### ISSUE TITLE
vim interface broken, new line on every keypress

### ISSUE THREAD

**Issue by jonaskuske** [felixse/FluentTerminal#97]
When using vi/vim, a new line is created on every keypress instead of overriding the current one(s).
So writing "Hi" looks like this:
```bash
~
H
~
Hi
~
```
The 'static interface' at the bottom (mode, filename, cursor position etc.) is duplicated as well every time, which pushes everything else up and out of the window - so before you scroll, you don't even see what you've written. Here is a GIF showing the issue:

![fluentissue](https://user-images.githubusercontent.com/30421456/46700896-5b70bb80-cc1e-11e8-81d1-365d8f397eab.gif)

Editing using nano works without problems and vim in Hyper also works flawlessly.

I'm using WSL (Ubuntu) on Windows 1809

**Comment by skipmeister123** [comment]
I've experienced this too.
--
Hans Kokx

**Comment by felixse** [comment]
Is this the released version (0.2.0.0) or current master? Also, did it work before updating to 1809?

**Comment by jonaskuske** [comment]
The released version.
Can't say if it worked on 1803, all my devices are on 1809 and I first installed FluentTerminal after the feature update.

**Comment by felixse** [comment]
This seems be fixed with the latest master. Probably the WinPTY update from #95

**Comment by Riebart** [comment]
I have had this crop up on me from time to time outside of vim, but not in any reproducible way. A new tab in the same window does not experience this issue when it rears its head in one of my tabs. I can confirm it's a thing, but can't offer any details to point to a cause.

**Comment by ad-on-is** [comment]
Same here, just had this problem outside of vim. 
After restarting FluentTerminal the problem persisted in the starting tab, while opening a new tab, did not have this kind of issue.

Prior to that I noticed that FT used 900MB of memory, which may be caused by the large log-outputs I'm monitoring during web-development with Docker. I've set the scrollback limit to 999999.

Maybe this helps.

![image](https://user-images.githubusercontent.com/9553253/47212024-5edf1200-d397-11e8-9d01-309b6ae968dd.png)

**Comment by StiviiK** [comment]
Similar issues when using `nano`

**Comment by nicohouillon** [comment]
in VI, if I want to move my cursor up/down it would print out character : A or B . I f I move right/left , then ir printout C or D .
only when I am in edition mode in VI  , after having pressed "I"or "A" .

**Comment by nicohouillon** [comment]
ok,  `set nocompatible` in ~/.vimrc fixed my problem above, still it was working fine in Windows Terminal Preview without this setting.
